server:
  port: 9295

spring:
  application:
    name: HYSTRIX-DASHBOARD

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'

turbine:
  appConfig: WRITING,READING
  clusterNameExpression: new String('default')
